-- OKB Commission approval and immutable monthly snapshot v123
-- Run once after the existing migrations.

create table if not exists public.commission_approvals (
  id bigint generated by default as identity primary key,
  period_from date not null,
  period_to date not null,
  comparison_from date not null,
  comparison_to date not null,
  branch_scope text not null default 'all',
  snapshot jsonb not null,
  total_net numeric not null default 0,
  total_base numeric not null default 0,
  total_rewards numeric not null default 0,
  total_penalties numeric not null default 0,
  total_orders integer not null default 0,
  signed_count integer not null default 0,
  rtd_count integer not null default 0,
  pending_count integer not null default 0,
  note text,
  override_reason text,
  status text not null default 'approved' check (status in ('approved','unlocked')),
  approved_by text not null,
  approved_by_user_id text,
  approved_at timestamptz not null default now(),
  unlocked_by text,
  unlocked_by_user_id text,
  unlocked_at timestamptz,
  unlock_reason text,
  constraint commission_approval_period_check check (period_from <= period_to and comparison_from <= comparison_to)
);

create unique index if not exists commission_approvals_active_period_uq
  on public.commission_approvals(period_from,period_to,comparison_from,comparison_to,branch_scope)
  where status='approved';

create index if not exists commission_approvals_period_idx
  on public.commission_approvals(period_from desc,period_to desc,status);

alter table public.commission_approvals enable row level security;
drop policy if exists okb_commission_approvals_admin_read on public.commission_approvals;
create policy okb_commission_approvals_admin_read on public.commission_approvals
  for select to authenticated
  using(lower(replace(replace(trim(private.okb_current_user_role()),' ','_'),'-','_'))='admin');

revoke insert,update,delete on public.commission_approvals from authenticated;
grant select on public.commission_approvals to authenticated;

create or replace function public.okb_approve_commission(
  p_period_from date,
  p_period_to date,
  p_comparison_from date,
  p_comparison_to date,
  p_snapshot jsonb,
  p_total_net numeric,
  p_total_base numeric,
  p_total_rewards numeric,
  p_total_penalties numeric,
  p_total_orders integer,
  p_signed_count integer,
  p_rtd_count integer,
  p_pending_count integer,
  p_note text default null,
  p_override_reason text default null,
  p_actor text default null
)
returns bigint
language plpgsql
security definer
set search_path=public,private
as $$
declare
  v_role text;
  v_actor text;
  v_id bigint;
begin
  v_role:=lower(replace(replace(trim(private.okb_current_user_role()),' ','_'),'-','_'));
  if v_role<>'admin' then raise exception 'اعتماد العمولة متاح للـAdmin فقط'; end if;
  if p_period_from>p_period_to or p_comparison_from>p_comparison_to then raise exception 'فترة العمولة غير صحيحة'; end if;
  if p_period_from<>date_trunc('month',p_period_from)::date or p_period_to<>(date_trunc('month',p_period_from)+interval '1 month - 1 day')::date then raise exception 'اعتماد العمولة يحتاج شهرًا ميلاديًا كاملًا'; end if;
  if p_period_to >= date_trunc('month',now() at time zone 'Africa/Cairo')::date then raise exception 'لا يمكن اعتماد العمولة قبل انتهاء الشهر'; end if;
  if p_snapshot is null then raise exception 'بيانات Snapshot غير موجودة'; end if;
  if coalesce(p_pending_count,0)>0 and length(btrim(coalesce(p_override_reason,'')))<3 then raise exception 'سبب الاعتماد الاستثنائي إجباري عند وجود Pending'; end if;
  perform pg_advisory_xact_lock(hashtext(concat(p_period_from,'|',p_period_to,'|',p_comparison_from,'|',p_comparison_to,'|all')));
  if exists(select 1 from public.commission_approvals where period_from=p_period_from and period_to=p_period_to and comparison_from=p_comparison_from and comparison_to=p_comparison_to and branch_scope='all' and status='approved') then
    raise exception 'هذه الفترة معتمدة بالفعل';
  end if;
  v_actor:=coalesce(nullif(btrim(p_actor),''),(select name from public."user" where id=auth.uid()),'Admin');
  insert into public.commission_approvals(period_from,period_to,comparison_from,comparison_to,branch_scope,snapshot,total_net,total_base,total_rewards,total_penalties,total_orders,signed_count,rtd_count,pending_count,note,override_reason,approved_by,approved_by_user_id)
  values(p_period_from,p_period_to,p_comparison_from,p_comparison_to,'all',p_snapshot,coalesce(p_total_net,0),coalesce(p_total_base,0),coalesce(p_total_rewards,0),coalesce(p_total_penalties,0),coalesce(p_total_orders,0),coalesce(p_signed_count,0),coalesce(p_rtd_count,0),coalesce(p_pending_count,0),nullif(btrim(p_note),''),nullif(btrim(p_override_reason),''),v_actor,auth.uid()::text)
  returning id into v_id;
  insert into public.activity_logs(user_id,user_name,username,user_role,action_type,action_title,action_details,branch_name,action_date,created_at)
  select null,v_actor,u.username,u.role,'commission_approved','اعتماد العمولة',format('الفترة: %s → %s | صافي الاستحقاق: %s | Pending: %s',p_period_from,p_period_to,p_total_net,p_pending_count),'Commission',(now() at time zone 'Africa/Cairo')::date,now()
  from (select 1) seed left join public."user" u on u.id=auth.uid();
  return v_id;
end;
$$;

create or replace function public.okb_unlock_commission_approval(p_approval_id bigint,p_reason text,p_actor text default null)
returns boolean
language plpgsql
security definer
set search_path=public,private
as $$
declare v_role text;v_actor text;v_row public.commission_approvals%rowtype;
begin
  v_role:=lower(replace(replace(trim(private.okb_current_user_role()),' ','_'),'-','_'));
  if v_role<>'admin' then raise exception 'فتح اعتماد العمولة متاح للـAdmin فقط'; end if;
  if length(btrim(coalesce(p_reason,'')))<3 then raise exception 'سبب فتح الاعتماد إجباري'; end if;
  select * into v_row from public.commission_approvals where id=p_approval_id for update;
  if not found or v_row.status<>'approved' then raise exception 'اعتماد العمولة غير موجود أو مفتوح بالفعل'; end if;
  v_actor:=coalesce(nullif(btrim(p_actor),''),(select name from public."user" where id=auth.uid()),'Admin');
  update public.commission_approvals set status='unlocked',unlocked_by=v_actor,unlocked_by_user_id=auth.uid()::text,unlocked_at=now(),unlock_reason=btrim(p_reason) where id=p_approval_id;
  insert into public.activity_logs(user_id,user_name,username,user_role,action_type,action_title,action_details,branch_name,action_date,created_at)
  select null,v_actor,u.username,u.role,'commission_unlocked','فتح اعتماد العمولة',format('الفترة: %s → %s | السبب: %s',v_row.period_from,v_row.period_to,btrim(p_reason)),'Commission',(now() at time zone 'Africa/Cairo')::date,now()
  from (select 1) seed left join public."user" u on u.id=auth.uid();
  return true;
end;
$$;

revoke all on function public.okb_approve_commission(date,date,date,date,jsonb,numeric,numeric,numeric,numeric,integer,integer,integer,integer,text,text,text) from public,anon;
grant execute on function public.okb_approve_commission(date,date,date,date,jsonb,numeric,numeric,numeric,numeric,integer,integer,integer,integer,text,text,text) to authenticated;
revoke all on function public.okb_unlock_commission_approval(bigint,text,text) from public,anon;
grant execute on function public.okb_unlock_commission_approval(bigint,text,text) to authenticated;
