-- OKB v162: unified filter center for order-status filters.
-- Additive only: this table controls filter display/availability and does not
-- update orders, stock, Signed logic, commissions, or financial calculations.

create table if not exists public.okb_filter_statuses (
  id bigint generated by default as identity primary key,
  filter_key text not null unique,
  display_name text not null,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_by uuid,
  updated_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint okb_filter_key_not_all check (btrim(filter_key) <> '' and btrim(filter_key) <> 'الكل'),
  constraint okb_filter_name_length check (char_length(btrim(display_name)) between 1 and 80)
);

create or replace function public.okb_touch_filter_status()
returns trigger
language plpgsql
security invoker
set search_path=public
as $$
begin
  new.filter_key := btrim(new.filter_key);
  new.display_name := btrim(new.display_name);
  new.updated_at := now();
  new.updated_by := auth.uid();
  if tg_op = 'INSERT' then
    new.created_by := coalesce(new.created_by, auth.uid());
  end if;
  return new;
end;
$$;

drop trigger if exists trg_okb_touch_filter_status on public.okb_filter_statuses;
create trigger trg_okb_touch_filter_status
before insert or update on public.okb_filter_statuses
for each row execute function public.okb_touch_filter_status();

alter table public.okb_filter_statuses enable row level security;

drop policy if exists okb_filter_statuses_read on public.okb_filter_statuses;
drop policy if exists okb_filter_statuses_admin_write on public.okb_filter_statuses;

create policy okb_filter_statuses_read on public.okb_filter_statuses
for select to authenticated
using (true);

create policy okb_filter_statuses_admin_write on public.okb_filter_statuses
for all to authenticated
using (private.okb_canonical_role(private.okb_current_user_role()) = 'admin')
with check (private.okb_canonical_role(private.okb_current_user_role()) = 'admin');

revoke all on public.okb_filter_statuses from public, anon;
grant select on public.okb_filter_statuses to authenticated;
grant insert, update, delete on public.okb_filter_statuses to authenticated;

do $$
begin
  if to_regclass('public.okb_filter_statuses_id_seq') is not null then
    execute 'grant usage, select on sequence public.okb_filter_statuses_id_seq to authenticated';
  end if;
end $$;

-- Seed the existing filters once. Re-running this migration never overwrites
-- names, visibility, or order already customized by the admin.
insert into public.okb_filter_statuses (filter_key, display_name, active, sort_order) values
  ('ZeroOrders', '🔴 أوردرات صفر', true, 10),
  ('Signed', 'Signed', true, 20),
  ('UrgentOrder', 'استعجال الأوردر', true, 30),
  ('ReplacementOrder', 'استبدال الأوردر', true, 40),
  ('ErrorOrder', 'أخطاء❌', true, 50),
  ('Transit', 'Transit', true, 60),
  ('Returned', 'Returned', true, 70),
  ('Fake Delivery update', 'Fake Delivery Update', true, 80),
  ('Fake Doctor', 'Fake Doctor', true, 90),
  ('Picked-up', 'Picked-up', true, 100),
  ('Delivering', 'Delivering', true, 110),
  ('Returning', 'Returning', true, 120),
  ('Cancel', 'Cancel', true, 130),
  ('PaymentProof', 'إثبات دفع', true, 140),
  ('SecretaryTransfers', 'تحويلات السكرتارية', true, 150),
  ('CollectionTransfers', 'تحويلات التحصيل من المندوب', true, 160)
on conflict (filter_key) do nothing;

-- Live propagation to already-open sessions when Supabase Realtime publication exists.
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
     and not exists (
       select 1 from pg_publication_tables
       where pubname = 'supabase_realtime'
         and schemaname = 'public'
         and tablename = 'okb_filter_statuses'
     ) then
    alter publication supabase_realtime add table public.okb_filter_statuses;
  end if;
end $$;

select '025_okb_filter_center installed successfully' as migration_status;
