-- OKB v192: Commission Settings Room
-- Requires migration 020 (private.okb_role_has_feature).
-- Supabase is the source of truth; values are versioned by effective month.

create table if not exists public.commission_settings (
  id bigint generated by default as identity primary key,
  effective_from date not null unique,
  tier_85_employee numeric(12,2) not null default 750 check (tier_85_employee >= 0),
  tier_85_manager numeric(12,2) not null default 3000 check (tier_85_manager >= 0),
  tier_87_employee numeric(12,2) not null default 1750 check (tier_87_employee >= 0),
  tier_87_manager numeric(12,2) not null default 5000 check (tier_87_manager >= 0),
  tier_90_employee numeric(12,2) not null default 2250 check (tier_90_employee >= 0),
  tier_90_manager numeric(12,2) not null default 6500 check (tier_90_manager >= 0),
  rtd_employee_per_point numeric(12,2) not null default 200 check (rtd_employee_per_point >= 0),
  rtd_manager_per_point numeric(12,2) not null default 200 check (rtd_manager_per_point >= 0),
  development_employee_per_point numeric(12,2) not null default 200 check (development_employee_per_point >= 0),
  development_manager_per_point numeric(12,2) not null default 200 check (development_manager_per_point >= 0),
  updated_by text not null default 'System Default',
  updated_by_user_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint commission_settings_month_start_check check (effective_from = date_trunc('month', effective_from)::date)
);

create index if not exists commission_settings_effective_from_idx
  on public.commission_settings(effective_from desc);

-- Legacy/current defaults apply to old periods until an Admin saves a newer month.
insert into public.commission_settings(
  effective_from,
  tier_85_employee,tier_85_manager,
  tier_87_employee,tier_87_manager,
  tier_90_employee,tier_90_manager,
  rtd_employee_per_point,rtd_manager_per_point,
  development_employee_per_point,development_manager_per_point,
  updated_by
)
values ('2000-01-01',750,3000,1750,5000,2250,6500,200,200,200,200,'System Default')
on conflict (effective_from) do nothing;

alter table public.commission_settings enable row level security;

drop policy if exists okb_commission_settings_read on public.commission_settings;
create policy okb_commission_settings_read on public.commission_settings
for select to authenticated
using (
  private.okb_role_has_feature('commission')
  or private.okb_role_has_feature('commission_settings_room')
);

-- Writes are performed only through the guarded RPC below.
revoke all on public.commission_settings from public,anon,authenticated;
grant select on public.commission_settings to authenticated;

create or replace function public.okb_save_commission_settings(
  p_effective_from date,
  p_tier_85_employee numeric,
  p_tier_85_manager numeric,
  p_tier_87_employee numeric,
  p_tier_87_manager numeric,
  p_tier_90_employee numeric,
  p_tier_90_manager numeric,
  p_rtd_employee_per_point numeric,
  p_rtd_manager_per_point numeric,
  p_development_employee_per_point numeric,
  p_development_manager_per_point numeric
)
returns public.commission_settings
language plpgsql
security definer
set search_path=public,private
as $$
declare
  v_actor text;
  v_row public.commission_settings%rowtype;
begin
  if not private.okb_role_has_feature('commission_settings_room') then
    raise exception 'غرفة العمولات غير مضافة لصلاحيات الـRole الخاصة بحسابك';
  end if;

  if p_effective_from is null or p_effective_from <> date_trunc('month',p_effective_from)::date then
    raise exception 'تاريخ التطبيق يجب أن يكون أول يوم في الشهر';
  end if;

  if p_tier_85_employee < 0 or p_tier_85_manager < 0
     or p_tier_87_employee < 0 or p_tier_87_manager < 0
     or p_tier_90_employee < 0 or p_tier_90_manager < 0
     or p_rtd_employee_per_point < 0 or p_rtd_manager_per_point < 0
     or p_development_employee_per_point < 0 or p_development_manager_per_point < 0 then
    raise exception 'قيم العمولات لا يمكن أن تكون سالبة';
  end if;

  select coalesce(nullif(btrim(name),''),nullif(btrim(username),''),'Authorized User')
    into v_actor
  from public."user"
  where id=auth.uid() and active is true
  limit 1;

  if v_actor is null then raise exception 'جلسة المستخدم غير صالحة'; end if;

  insert into public.commission_settings(
    effective_from,
    tier_85_employee,tier_85_manager,
    tier_87_employee,tier_87_manager,
    tier_90_employee,tier_90_manager,
    rtd_employee_per_point,rtd_manager_per_point,
    development_employee_per_point,development_manager_per_point,
    updated_by,updated_by_user_id,updated_at
  ) values (
    p_effective_from,
    p_tier_85_employee,p_tier_85_manager,
    p_tier_87_employee,p_tier_87_manager,
    p_tier_90_employee,p_tier_90_manager,
    p_rtd_employee_per_point,p_rtd_manager_per_point,
    p_development_employee_per_point,p_development_manager_per_point,
    v_actor,auth.uid()::text,now()
  )
  on conflict (effective_from) do update set
    tier_85_employee=excluded.tier_85_employee,
    tier_85_manager=excluded.tier_85_manager,
    tier_87_employee=excluded.tier_87_employee,
    tier_87_manager=excluded.tier_87_manager,
    tier_90_employee=excluded.tier_90_employee,
    tier_90_manager=excluded.tier_90_manager,
    rtd_employee_per_point=excluded.rtd_employee_per_point,
    rtd_manager_per_point=excluded.rtd_manager_per_point,
    development_employee_per_point=excluded.development_employee_per_point,
    development_manager_per_point=excluded.development_manager_per_point,
    updated_by=excluded.updated_by,
    updated_by_user_id=excluded.updated_by_user_id,
    updated_at=now()
  returning * into v_row;

  return v_row;
end;
$$;

revoke all on function public.okb_save_commission_settings(date,numeric,numeric,numeric,numeric,numeric,numeric,numeric,numeric,numeric,numeric) from public,anon;
grant execute on function public.okb_save_commission_settings(date,numeric,numeric,numeric,numeric,numeric,numeric,numeric,numeric,numeric,numeric) to authenticated;

select '026_commission_settings_room installed successfully' as migration_status;
